version: '3'

services:
  mongodb:
    image: wiremock/wiremock:latest-alpine
    container_name: iac_wiremock
    ports:
      - '8080:8080'
    network_mode: bridge
    volumes:
      - ./config:/home/wiremock