version: '3'

volumes:
  mongodb_data:

services:
  mongodb:
    image: mongo:6
    container_name: iac_mongodb
    ports:
      - '27017:27017'
    network_mode: bridge
    volumes:
      - mongodb_data:/data/db
      - ./config/initdb.js:/docker-entrypoint-initdb.d/initdb.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: iac
      MONGO_INITDB_ROOT_PASSWORD: iac_pwd
      MONGO_INITDB_DATABASE: iac_adm